jwt:
  secret: ${JWT_SECRET}
  accessTokenExpireTime: ${JWT_ACCESS_EXPIRE_TIME}
  refreshTokenExpireTime: ${JWT_REFRESH_EXPIRE_TIME}

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100

spring:
  config:
    import: optional:file:.env
  profiles:
    include:
      - domain
      - common
      - batch
      - infrastructure
      - external
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.web.cors: DEBUG