jwt:
  secret: ${JWT_SECRET}
  accessTokenExpireTime: ${JWT_ACCESS_EXPIRE_TIME}
  refreshTokenExpireTime: ${JWT_REFRESH_EXPIRE_TIME}
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  profiles:
    active: dev
    include:
      - domain
      - external
      - infrastructure
  config:
    import: optional:file:.env[.properties]
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.web.cors: DEBUG