spring:
  config:
    import: optional:file:.env[.properties]

feign:
  kakao:
    name: ${KAKAO_NAME}
    get-token-url: ${KAKAO_GET_TOKEN_URL}
    get-token-info-url: ${KAKAO_GET_TOKEN_INFO_URL}
    redirect: ${KAKAO_REDIRECT}
    rest-api-key: ${KAKAO_REST_API_KEY}