version: '3.7'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    environment:
      REDIS_TIMEOUT: 2000ms
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - tic-toc-net
  tictoc-blue:
    image: mungzogi/tictoc-api:latest
    container_name: tictoc-blue
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8081:8080"
    networks:
      - tic-toc-net

networks:
  tic-toc-net:
    name: tic-toc-net
    external: true